### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by josef0731** [Fraternalilab/PDBencode#2]
I struggled in installing the R package in MacOS. While I am almost certain this has to do with dependencies etc, I am too impatient with deciphering what packages/libraries I am missing ...

I quickly set up this Dockerfile to create a docker image with the package installed - I thought maybe it's an alternative?

Dockerfile:

```
FROM r-base
RUN apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev libxml2-dev libgsl-dev

RUN R -q -e "install.packages(c('devtools', 'bio3d'))"
RUN R -q -e "library('devtools'); install_github('Fraternalilab/PDBencode')"

RUN /bin/bash
```

And then one can build this image, fire up a docker container and run the PDBencode Rscript as such - running this in the directory containing the R script (i.e. `pdbencode.R` provided in this repo) and your PDB files:

```
#!/bin/bash

# initiate docker container
docker run -v `pwd`:/data -w /data --user "$(id -u):$(id -g)" --name pdbencodedocker --cidfile test.cid -itd pdbencode
cid=$(cat test.cid)

# run pdbencode inside the container
echo "Running PDBencode ..."
docker exec -it pdbencodedocker Rscript pdbencode.R

# clean up (remove exited docker containers)
docker stop $cid
docker rm $(docker ps -q -f status=exited)
rm test.cid

```

**Comment by jkleinj** [comment]
The latest release v.0.4.3 cointains an update of your scripts in inst/tools that allows for Docker execution of popscomp.R.
